### ISSUE TITLE
Unable to upgrade due to backup fail

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/agendav_ynh#34]
Hi,

The upgrade failed because of the error below:

I am not entirely sure this is a bug but I guess the backup output directory should either be cleaned or a new name should be generated for the backup?

```
2018-12-30 15:27:57,496: WARNING - The output directory is not empty
2018-12-30 15:27:57,601: WARNING - Backup failed, the upgrade process was aborted.
2018-12-30 15:27:57,715: ERROR - Impossible de mettre à jour agendav
```

**Comment by maniackcrudelis** [comment]
> ```2018-12-30 15:27:57,496: WARNING - The output directory is not empty```

That's half a bug half a feature, that's something that happens when the backup crash or is killed before the end of its execution. The directory isn't empty, and the backup can't continue.

You should open a issue about that on the [bug tracker](https://github.com/YunoHost/issues/issues). And meanwhile, you can clean the tmp directory `/home/yunohost.backup/tmp`
